### ISSUE TITLE
Fighting your own avatar

### ISSUE THREAD

**Issue by kparaskev** [zinas/thegrid#1]
After the first login or whenever you refresh the game page under avatars your character avatar is displayed, with the option to Fight. Clicking on Fight will allow you to fight yourself, and give you also reward xp and money.

Screenshot of fight button: http://i.imgur.com/Vv9BpUp.png
Screenshot of result after fighting yourself: http://i.imgur.com/o1ofRir.png

**Comment by zinas** [comment]
You no longer see your avatar
