### ISSUE TITLE
Soldier skill "Personal Medpac" not working.

### ISSUE THREAD

**Issue by jimzinas** [zinas/thegrid#4]
I lost some hp on same level minions (level 4) and then started fighting lvl 1 minions to track if the skill works and I dont seem to be regenerating the hp I am supposed to. Also in the skill description the chance % per level is undefined.

**Comment by zinas** [comment]
@jimzinas Can you test this, if it's working now?

**Comment by jimzinas** [comment]
It's working now

**Comment by jimzinas** [comment]
After a few more tests I beleive it has to be nerfed a bit... I lose almost no life at all or replentish the lost one because I heal 5 every round.

**Comment by zinas** [comment]
Agree, will nerf it, but I am closing this ticket because the original issue is solved
