### ISSUE TITLE
Equipment tab crash

### ISSUE THREAD

**Issue by jimzinas** [zinas/thegrid#8]
I dont know if its me but whenever I press on the "equipment" tab nothing happens and after that I cannot change tabs anymore (my avatar, avatar upgrades etc) and I have to refresh the page.

**Comment by SirLeon** [comment]
got same problem, but I think it started after I had equipped all three equipment slots

**Comment by zinas** [comment]
this should be fixed now

**Comment by jimzinas** [comment]
nope, still crashes.

**Comment by zinas** [comment]
Sorry, minor mistake, now it's ok
